### ISSUE TITLE
Use system installed jekyll

### ISSUE THREAD

**Issue by hrnn** [L-A/Little-Jekyll#9]
Hi
First of all awesome project.
I tried to compile an existing documentation that uses github-pages gem, I noticed then that a version of jekyll is bundled with the app including gems.
Is it possible to use system installed jekyll instead of the bundled one? or how can I add a new gem into the app?

Thanks in advance

**Comment by L-A** [comment]
Hi @hrnn! Thanks so much for trying it out.

You're describing something I explored initially. Since the goal of the project is to help discover Jekyll, I debated whether to make the app perform a guided install to the system or come with its packaged version of Jekyll.

I ended up going with a packaged Jekyll because I can't reliably plan for all systems' particularities. Questions like these would all have to be accounted for:
- Do I have to interact with `rvm` or `rbenv` or `chruby`?
- If not, what is the Ruby version installed? Which Jekyll version can I run on this?
- Is Jekyll run by itself or through `bundler`?
- Are these conclusions reliable system-wide or should I try to infer from individual Jekyll projects?

This said, there are a couple of gems that I'd consider bundling into [Traveling Jekyll](https://github.com/L-A/Traveling-Jekyll) directly. Anything considered of "mainstream" use for Jekyll sites would be reasonable. `github-pages` is pretty much the first one that comes to mind. Once packaged there, it will exist into the next Little Jekyll release.

If you want to dive into it, you can certainly package your own Traveling Jekyll with added gems! It's much easier doing it for only one OS. Replace the `/jekyll` directory inside `Little Jekyll.app` and it will run your package instead :)

**Comment by L-A** [comment]
I took a few minutes to test it out.

Here's an experimental package including Jekyll 3.2.1 and the `github-pages` gem, it built fine but I'm wary of Nokogiri having installed new native extensions (a potential issue with Traveling Ruby). It runs well on my side, both when invoked from the terminal and when put inside the distributed app.

Name it `jekyll` and replace `/Content/Resources/app/jekyll/` in the app. Tell me if it all works out!

[traveling-jekyll-3.1.2b-osx.tar.gz](https://github.com/L-A/Little-Jekyll/files/527498/traveling-jekyll-3.1.2b-osx.tar.gz)

**Comment by hrnn** [comment]
Thanks @L-A `github-pages` is working, closing the issue.

**Comment by L-A** [comment]
Great! Thanks for confirming.
